# build petclinic image
FROM maven:3.8.4-openjdk-17-slim as builder

WORKDIR /app

# Clone the Spring PetClinic repository
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/spring-projects/spring-petclinic.git

WORKDIR /app/spring-petclinic

RUN mvn package -Dmaven.test.skip=true

FROM openjdk:17-jdk-slim

WORKDIR /app/

COPY --from=builder /app/spring-petclinic/target/*.jar /app/petclinic.jar

EXPOSE 8080

CMD ["java", "-jar", "petclinic.jar"]