# build petclinic image
FROM maven

WORKDIR /app

COPY ./spring-petclinic .

RUN mvn package

FROM openjdk:11-jdk-slim

WORKDIR /app

COPY --from=0 /app/target/*.jar /app/petclinic.jar

EXPOSE 8080

CMD ["java", "-jar", "petclinic.jar"]